In [100]:
import pandas as pd
import numpy as np
import sklearn as sns

In [101]:
df = pd.read_csv("insurance_data.csv")

In [102]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830
1334,18,female,31.920,0,no,northeast,2205.98080
1335,18,female,36.850,0,no,southeast,1629.83350
1336,21,female,25.800,0,no,southwest,2007.94500


In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [104]:
df.isnull()

,age,gender,bmi,children,smoker,region,charges
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
1333,False,False,False,False,False,False,False
1334,False,False,False,False,False,False,False
1335,False,False,False,False,False,False,False
1336,False,False,False,False,False,False,False


In [105]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [106]:
df.value_counts()

age  gender  bmi     children  smoker  region     charges    
19   male    30.590  0         no      northwest  1639.56310     2
18   female  38.280  0         no      southeast  1631.82120     1
64   female  33.800  1         yes     southwest  47928.03000    1
             32.965  0         no      northwest  14692.66935    1
18   female  30.115  0         no      northeast  2203.47185     1
                                                                ..
64   female  26.885  0         yes     northwest  29330.98315    1
             30.115  3         no      northwest  16455.70785    1
             31.300  2         yes     southwest  47291.05500    1
             31.825  2         no      northeast  16069.08475    1
63   male    28.310  0         no      northwest  13770.09790    1
Name: count, Length: 1337, dtype: int64

In [107]:
df.duplicated().sum()

np.int64(1)

In [108]:
df.drop_duplicates(inplace=True)

In [109]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [110]:
gender ={
    'female':0, 'male':1
}

In [111]:
df['gender']=df['gender'].map(gender)


In [112]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,yes,southwest,16884.92400
1,18,1,33.770,1,no,southeast,1725.55230
2,28,1,33.000,3,no,southeast,4449.46200
3,33,1,22.705,0,no,northwest,21984.47061
4,32,1,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,no,northwest,10600.54830
1334,18,0,31.920,0,no,northeast,2205.98080
1335,18,0,36.850,0,no,southeast,1629.83350
1336,21,0,25.800,0,no,southwest,2007.94500


In [113]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [114]:
smoker ={
    'yes':1, 'no':0
}

In [115]:
df['smoker']=df['smoker'].map(smoker)


In [116]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [117]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [118]:
#region ={
    #'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
#}

In [119]:
#df['region']=df['region'].map(region)


In [120]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [121]:
df.duplicated().sum()

np.int64(0)

In [122]:
x=df.drop(columns=['charges','region'])
y=df['charges']


In [123]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [124]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [125]:
x.duplicated().sum()

np.int64(2)

In [126]:
#x.drop_duplicates(inplace=True)

In [127]:
y.duplicated().sum()

np.int64(0)

In [128]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [129]:
x_train

,age,gender,bmi,children,smoker
1114,23,1,24.510,0,0
968,21,1,25.745,2,0
599,52,0,37.525,2,0
170,63,1,41.470,0,0
275,47,0,26.600,2,0
...,...,...,...,...,...
1096,51,0,34.960,2,1
1131,27,1,45.900,2,0
1295,20,1,22.000,1,0
861,38,0,28.000,3,0


In [130]:
x_test

,age,gender,bmi,children,smoker
900,49,1,22.515,0,0
1064,29,0,25.600,4,0
1256,51,0,36.385,3,0
298,31,1,34.390,3,1
237,31,1,38.390,2,0
...,...,...,...,...,...
534,64,1,40.480,0,0
542,63,0,36.300,0,0
760,22,0,34.580,2,0
1284,61,1,36.300,1,1


In [131]:
y_train

1114     2396.09590
968      3279.86855
599     33471.97189
170     13405.39030
275      9715.84100
           ...     
1096    44641.19740
1131     3693.42800
1295     1964.78000
861      7151.09200
1127     5836.52040
Name: charges, Length: 1069, dtype: float64

In [132]:
y_test

900      8688.85885
1064     5708.86700
1256    11436.73815
298     38746.35510
237      4463.20510
           ...     
534     13831.11520
542     13887.20400
760      3925.75820
1284    47403.88000
1285     8534.67180
Name: charges, Length: 268, dtype: float64

In [133]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(1069, 5) (268, 5) (1069,) (268,)


In [134]:
x_train, x_test, y_train, y_test = x_train, x_test, y_train, y_test.drop_duplicates()

In [135]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [136]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,0,27.900,0,1,southwest,16884.92400
1,18,1,33.770,1,0,southeast,1725.55230
2,28,1,33.000,3,0,southeast,4449.46200
3,33,1,22.705,0,0,northwest,21984.47061
4,32,1,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,northwest,10600.54830
1334,18,0,31.920,0,0,northeast,2205.98080
1335,18,0,36.850,0,0,southeast,1629.83350
1336,21,0,25.800,0,0,southwest,2007.94500


In [137]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()


In [138]:
lr.fit(x_train,y_train)


,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [139]:
lr.score(x_train,y_train)

0.7292291093848736

In [149]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [150]:
import joblib

In [151]:
joblib.dump(lr,'insurance_joblib')

['insurance_joblib']

In [143]:
model=joblib.load('insurance_joblib')


In [144]:
southwest = lr.predict(x_test)

In [145]:
southwest

array([ 7780.09204548,  5977.83338997, 14215.82300956, 31590.59473466,
        9223.64922442, 13438.43822409, 29841.65667782,  1685.03795715,
       10919.46514725, 11281.04050309, 10418.78669104, 33059.36084168,
       30531.50988264, 17420.0023959 , 10214.90616935,  9749.75223135,
        4298.47335596, 32007.67725019,  3488.96062241,  5583.27330599,
        3845.53703027, 29815.02239719, 15103.39914515, 30646.34708594,
       30908.30211535,  5363.08477297, 35705.172843  , 36714.56751572,
       10928.83748576, 13689.22034633,  5994.25520485, 13015.10761713,
         842.10884744, 12332.40611586, 39769.78804625, 12472.16793437,
        4941.6340669 ,  3962.34504306, 31334.30270026,  9347.27340131,
        6423.31161511, 29743.01929574, 35062.57980736, 11806.50755259,
        7409.90515685,  3638.00400509,  5572.08908023,  9165.34126485,
        4217.22289854,  9367.5521687 ,  6914.22550367, 11443.85328341,
       30801.79761652,  3861.35683277, 11172.20169464, 10108.79403925,
      

In [146]:
x

,age,gender,bmi,children,smoker
0,19,0,27.900,0,1
1,18,1,33.770,1,0
2,28,1,33.000,3,0
3,33,1,22.705,0,0
4,32,1,28.880,0,0
...,...,...,...,...,...
1333,50,1,30.970,3,0
1334,18,0,31.920,0,0
1335,18,0,36.850,0,0
1336,21,0,25.800,0,0


In [147]:
lr.predict([[19,	0,	27.900,	0,	1]])

c:\Users\anand\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25089.26781169])

In [148]:
lr.predict(x_train)

array([ 1913.28139775,  2868.42936746, 14275.33486501, ...,
         936.91190884,  8415.15856955,  9531.89800259], shape=(1069,))